-- ============================================================================
--  Control Local — Esquema de base de datos (Supabase / PostgreSQL)
-- ============================================================================
--  Cómo usarlo:
--    1. En tu proyecto de Supabase, abre "SQL Editor".
--    2. Pega TODO este archivo y dale "Run".
--    3. Es idempotente: puedes volver a correrlo sin romper nada.
--
--  Modelo:
--    - Multi-negocio: cada usuario pertenece a UN negocio y solo ve sus datos.
--    - Cada entidad (venta, producto, cliente…) se guarda como un registro con
--      su contenido en una columna JSONB `data`, para calzar 1:1 con la app.
--    - RLS (Row Level Security) activo en todo: el aislamiento entre negocios
--      lo impone la base de datos, no la app.
--    - Al registrarse un usuario, se le crea automáticamente su negocio + perfil.
-- ============================================================================

-- ----------------------------------------------------------------------------
--  1. Identidad: negocios y perfiles de usuario
-- ----------------------------------------------------------------------------

create table if not exists public.negocios (
  id          uuid primary key default gen_random_uuid(),
  nombre      text not null default 'Mi negocio',
  created_at  timestamptz not null default now()
);

-- Un perfil por usuario de auth. Lo vincula a su negocio y guarda su rol.
create table if not exists public.perfiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  negocio_id  uuid not null references public.negocios(id) on delete cascade,
  nombre      text,
  rol         text not null default 'admin'
              check (rol in ('admin', 'vendedor', 'bodega', 'contador')),
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);
create index if not exists perfiles_negocio_idx on public.perfiles(negocio_id);

-- Devuelve el negocio del usuario actual. SECURITY DEFINER para que las
-- políticas RLS de otras tablas puedan consultarlo sin recursión.
create or replace function public.current_negocio_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select negocio_id from public.perfiles where id = auth.uid();
$$;

-- ----------------------------------------------------------------------------
--  2. Tablas de colección (una fila por entidad, contenido en JSONB `data`)
-- ----------------------------------------------------------------------------

-- Productos: id NUMÉRICO (la app usa Product.id: number y SaleItem.productId).
create table if not exists public.productos (
  id          bigint generated by default as identity primary key,
  negocio_id  uuid not null references public.negocios(id) on delete cascade,
  data        jsonb not null,
  created_at  timestamptz not null default now()
);
create index if not exists productos_negocio_idx on public.productos(negocio_id);

-- Resto de entidades: id de texto (la app genera UUIDs con la librería `uuid`).
do $$
declare t text;
begin
  foreach t in array array[
    'ventas', 'clientes', 'movimientos', 'gastos', 'nomina',
    'marketing', 'metas', 'creditos', 'proveedores', 'cierres', 'formatos', 'despachos'
  ]
  loop
    execute format($f$
      create table if not exists public.%I (
        id          text primary key default gen_random_uuid()::text,
        negocio_id  uuid not null references public.negocios(id) on delete cascade,
        data        jsonb not null,
        created_at  timestamptz not null default now()
      );
    $f$, t);
    execute format(
      'create index if not exists %I on public.%I(negocio_id);',
      t || '_negocio_idx', t
    );
  end loop;
end $$;

-- ----------------------------------------------------------------------------
--  3. Tablas singleton por negocio (configuración y categorías)
-- ----------------------------------------------------------------------------

create table if not exists public.configuracion (
  negocio_id  uuid primary key references public.negocios(id) on delete cascade,
  data        jsonb not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);

create table if not exists public.categorias (
  negocio_id  uuid primary key references public.negocios(id) on delete cascade,
  lista       jsonb not null default '[]'::jsonb,
  updated_at  timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
--  4. Row Level Security: cada negocio ve solo lo suyo
-- ----------------------------------------------------------------------------

-- negocios
alter table public.negocios enable row level security;
drop policy if exists negocios_select on public.negocios;
create policy negocios_select on public.negocios
  for select using (id = public.current_negocio_id());
drop policy if exists negocios_update on public.negocios;
create policy negocios_update on public.negocios
  for update using (id = public.current_negocio_id())
  with check (id = public.current_negocio_id());

-- perfiles
alter table public.perfiles enable row level security;
drop policy if exists perfiles_select on public.perfiles;
create policy perfiles_select on public.perfiles
  for select using (id = auth.uid() or negocio_id = public.current_negocio_id());
-- Cada usuario solo puede actualizar SU PROPIO perfil (no el de otros miembros).
drop policy if exists perfiles_update on public.perfiles;
create policy perfiles_update on public.perfiles
  for update using (id = auth.uid())
  with check (id = auth.uid() and negocio_id = public.current_negocio_id());

-- Tablas de colección + singletons: una política FOR ALL por negocio_id.
do $$
declare t text;
begin
  foreach t in array array[
    'productos', 'ventas', 'clientes', 'movimientos', 'gastos', 'nomina',
    'marketing', 'metas', 'creditos', 'proveedores', 'cierres', 'formatos', 'despachos',
    'configuracion', 'categorias'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists %I on public.%I;', t || '_rw', t);
    execute format($p$
      create policy %I on public.%I
        for all
        using (negocio_id = public.current_negocio_id())
        with check (negocio_id = public.current_negocio_id());
    $p$, t || '_rw', t);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
--  5. Permisos para el rol `authenticated` (las filas las filtra RLS)
-- ----------------------------------------------------------------------------

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;

-- ----------------------------------------------------------------------------
--  6. Auto-provisión: al registrarse un usuario, crear su negocio + perfil
--     (+ configuración y categorías por defecto, para que la app no abra vacía)
-- ----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  nid uuid;
begin
  insert into public.negocios (nombre) values ('Mi negocio') returning id into nid;

  insert into public.perfiles (id, negocio_id, nombre, rol)
  values (
    new.id,
    nid,
    coalesce(new.raw_user_meta_data->>'nombre', split_part(new.email, '@', 1)),
    'admin'
  );

  insert into public.configuracion (negocio_id, data)
  values (nid, jsonb_build_object(
    'business', 'Mi negocio',
    'currency', 'Peso chileno (CLP)',
    'methods', jsonb_build_array('Efectivo', 'Transferencia', 'Tarjeta'),
    'minStockDefault', 5,
    'minMargin', 20
  ));

  insert into public.categorias (negocio_id, lista)
  values (nid, jsonb_build_array('Abarrotes', 'Bebidas', 'Limpieza', 'Otros'));

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
--  Fin del esquema.
-- ============================================================================
